default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= Rails.application.credentials.Database_Development[:Password] %>
  host: <%= Rails.application.credentials.Database_Development[:Host] %>

development:
  <<: *default
  database: Music_Player

# test:
#   <<: *default
#   database: Music_Player_test

production:
  <<: *default
  database: Music_Player
  username: root
  password: <%= Rails.application.credentials.Database_Production[:Password] %>
  host: <%= Rails.application.credentials.Database_Production[:Host] %>
